/**
 * @file writeparameters.cpp
 * @brief Writes model parameters into a file.
 *
 * User calls Export_parameters().
 *
 * Supported file formats: MorphoMaker, Humppa.
 *
 */

#include <stdio.h>
#include <vector>
#include <iostream>
#include <QString>

#include "parameters.h"
#include "utils/writeparameters.h"
#include "morphomaker.h"


namespace {

/**
 * @brief Writes native format parameters file.
 * @param parameters    Parameters object.
 * @param outname       File name with full path.
 * @return              0 if success, else -1.
 */
int Write_parameters_MorphoMaker(Parameters *parameters, const char *outname)
{
    uint16_t i;

    FILE* output = fopen(outname, "w");
    if (output == NULL) {
        fprintf(stderr, "Error: Can't open file '%s' for writing.\n", outname);
        return -1;
    }

    #if defined(__linux__)
    char *oldloc = setlocale(LC_ALL, "C");
    #endif

    fprintf(output, "# Model parameters file generated by MorphoMaker %s.\n", MMAKER_VERSION);
    fprintf(output, "# NOTE: Parameter names are case-sensitive, while non-parameter keywords\n");
    fprintf(output, "# (e.g. model, viewtresh) are case-insensitive!\n");
    fprintf(output, "\n");

    auto keywords = parameters->getKeywords();
    if (keywords == NULL) {
        fclose(output);
        return -1;
    }

    fprintf(output, "# Model name, view threshold, view mode, iterations.\n");
    for (i=0; i<keywords->size(); i++) {
        fprintf(output, "%s==%s\n", keywords->at(i).c_str(),
                        parameters->getKey(keywords->at(i)).c_str());
    }
    fprintf(output, "\n");

    auto names = parameters->getParNames();
    if (names == NULL) {
        fclose(output);
        return -1;
    }

    fprintf(output, "# Parameters.\n");
    for (i=0; i<names->size(); i++) {
        auto name = names->at(i);

        if (!parameters->isParameterHidden(name)) {
            fprintf( output, "%s==%.7f\n", name.c_str(),
                             parameters->getParValues()->at(i) );
        }
    }

    #if defined(__linux__)
    setlocale(LC_ALL, oldloc);
    #endif

    fclose(output);

    return 0;
}



/**
 * @brief Writes parameter file for humppa, humppa_translate.
 * @param parameters    Parameters object.
 * @param outname       File name with full path.
 * @return              0 if success, else -1.
 */
int Write_parameters_Humppa(Parameters *parameters, const char *outname)
{
    FILE* output = fopen(outname, "w");
    if (output == NULL) {
        fprintf(stderr, "Error: Can't open file '%s' for writing.\n", outname);
        return -1;
    }

    #if defined(__linux__)
    char *oldloc = setlocale(LC_ALL, "C");
    #endif

    auto names = parameters->getParNames();
    if (names == NULL) {
        fclose(output);
        return -1;
    }

    for (uint16_t i=0; i<names->size(); i++) {
        fprintf(output, "%.7f #\n", parameters->getParValues()->at(i));
    }

    #if defined(__linux__)
    setlocale(LC_ALL, oldloc);
    #endif

    fclose(output);

    return 0;
}

}



/**
 * @brief Writes current model parameters into a text file in given format.
 * @param par       Parameters object.
 * @param file      File name with full path.
 * @param format    Export file format.
 * @return          0 if sucess, else -1.
 */
int morphomaker::Export_parameters(Parameters *par, const std::string file,
                                   const QString& format)
{
    if (par == NULL) {
        return -1;
    }

    int rv = -1;
    if (format == PROGRAM_NAME) {
        rv = Write_parameters_MorphoMaker(par, file.c_str());
    }
    else if (format == "Humppa") {
        rv = Write_parameters_Humppa(par, file.c_str());
    }
    else {
        std::cerr << "Fatal error: Unknown input format '"
                  << format.toStdString()
                  << "'. Please check <InputStyle> in the model XML file. "
                  << std::endl;
    }

    return rv;
}
